### ISSUE TITLE
[SPIKE] Review parameter validation toolkits

### ISSUE THREAD

**Issue by mnyon-grandkru** [Githubbubber/gsn-audio-review-app#2]
The functions that handle these endpoints have a common pattern.  They:
* Analyze & validate input
* Make request to server
* Parses results from that request

Do a comparison and contrast with [express-validator](https://express-validator.github.io/docs/) and other tools to determine which ones are the best both in general and for this app's needs in particular.

I do believe there's a way to reduce the lines of code from 
```
const { username, password } = req.body;

  const isValid = username !== undefined && password !== undefined
                  && username !== 0 && password !== 0 
                  && username !== null && password !== null
                  && username !== "" && password !== ""
                  && username.match(/[A-Za-z0-9 ,.!-]/g) && !password.match(/[^LTa-z-]/g)
                  && password.length === 25;

  if (!isValid) res.status(403).send("Information not accepted");

  const visitor_role = password === process.env.SECRET_ENTRY_ADMIN_VALUE ? 
                      "admin" : password === process.env.SECRET_ENTRY_REVIEWER_VALUE ? 
                      "reviewer" : null;

  if (visitor_role) {
    const reroute_loc = visitor_role === "reviewer" ? 
                        "/review" : "/admin";

    const country_loc = req.rawHeaders[9];
    const device_info = req.rawHeaders[22] + " - " + req.rawHeaders[23];

    const current_date = new Date();

    const login_values = [ username, country_loc, device_info, visitor_role, current_date ];
```

to something more manageable.

**Comment by Githubbubber** [comment]
So far, what I know about express-validator is that it takes care of all common coverage needed for input validation in the front-end. Fortunately it looks to still be supported and is also popular with developers. It has a few bugs reported but doesn't have as many issues open as I've seen with other npm packages. Through researching other packages I see how others just don't compare either in maintenance, popularity (and through that a reputation), or ease for me.

**Comment by Githubbubber** [comment]
Validations added in PR #7
